sudo: required

language: ruby

services:
  - docker

before_install:
  - docker run -it -v $(pwd):/home/feedem vbatts/pandoc -f markdown_github -t latex -o /home/feedem/docs/README.pdf /home/feedem/docs/README.md

after_success:
  - ./push.sh
