sudo: required

language: ruby


services:
- docker

before_install:
- chmod +x push.sh
- ./push.sh

install:
- docker-compose build

script:
- docker-compose run web rails db:create
- docker-compose run web rails db:migrate
- docker-compose run web rails db:test:prepare
- docker-compose run -e 'RAILS_ENV=test' web rails webpacker:compile
- docker-compose run web rails test
