sudo: required

language: ruby

services:
  - docker

before_install:
  - docker run -it --mount src=$TRAVIS_BUILD_DIR,target=/home/feedem,type=bind vbatts/pandoc -f markdown -t latex -o /home/feedem/docs/README.pdf --pdf-engine=xelatex  -V mainfont="DejaVu Sans Mono" /home/feedem/README.md


after_success:
  - ./push.sh
