sudo: required

language: ruby

addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
    - pandoc

services:
  - docker

before_install:
  - pandoc -f markdown_github -t latex -V mainfont="DejaVu Sans Mono" -o docs/README.pdf README.md

after_success:
  - ./push.sh
