version: '3'
services:
  db:
    image: postgres
    volumes:
    - ./app/tmp/db:/var/lib/postgresql/data
  web:
    image: kolaer/feedem_web
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
    - ./app:/myapp
    ports:
    - "3000:3000"
    depends_on:
    - db
    - webpacker
  webpacker:
    image: kolaer/feedem_web
    command: bundle exec bin/webpack-dev-server
    volumes:
    - ./app:/myapp
    ports:
    - "8080:8080"
  adminer:
    image: adminer
    restart: always
    ports:
    - 4352:8080
